# Enable logging
CONFIG_LOG=y

# Enable ztest
CONFIG_ZTEST=y

# Useful for double checking the code location in the disassembly
CONFIG_OUTPUT_DISASSEMBLY=y

# Enable the minimal call driver.
CONFIG_IRONSIDE_SE_CALL_MINIMAL=y

CONFIG_MULTITHREADING=n
